"""Port viewer.html into the Shopify theme: sections/pm2-cat-town.liquid + assets/pm2-cat-city.js (ids prefixed pcc-, CSS scoped to .pm2-city).
Usage: python3 build_shopify.py  (run from social/cat-town after build_viewer.py)."""
import re
T = '../../shopify-theme-tech/'
v = open('viewer.html').read()
shell, mod = v.split('<script type="module">', 1)
js = mod.rsplit('</script>', 1)[0]
css = re.search(r'<style>(.*?)</style>', shell, re.S).group(1)
city = re.search(r'<script>window.CITY = (.*?);</script>', shell, re.S).group(1)
body = shell.split('</style>', 1)[1]
body = re.sub(r'<script>window.CITY = .*?</script>', '', body, flags=re.S)
body = re.sub(r'<script type="importmap">.*?</script>', '', body, flags=re.S)
E = 'https://cdn.jsdelivr.net/npm/three@0.170.0/'
js = js.replace("import * as THREE from 'three';", f"import * as THREE from '{E}+esm';")
js = js.replace("import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';", f"import {{ mergeGeometries }} from '{E}examples/jsm/utils/BufferGeometryUtils.js/+esm';")
js = js.replace("import { OrbitControls } from 'three/addons/controls/OrbitControls.js';", f"import {{ OrbitControls }} from '{E}examples/jsm/controls/OrbitControls.js/+esm';")
assert "const $ = id => document.getElementById(id);" in js
js = js.replace("const $ = id => document.getElementById(id);", "const ROOT = document.querySelector('[data-cat-city]'); const $ = id => document.getElementById('pcc-' + id);")
js = js.replace("document.getElementById('stage')", "$('stage')").replace("document.querySelectorAll('[data-f]')", "ROOT.querySelectorAll('[data-f]')")
js = js.replace("document.body.classList.add('ready');", "ROOT.classList.add('ready');").replace("document.querySelector('.ui')", "ROOT")
left = re.findall(r"document\.getElementById\((?!'pcc-' \+ id)[^)]*\)", js); assert not left, left
body = re.sub(r'\bid="([\w-]+)"', r'id="pcc-\1"', body)
body = re.sub(r'\bfor="([\w-]+)"', r'for="pcc-\1"', body)
body = re.sub(r'aria-labelledby="([\w-]+)"', r'aria-labelledby="pcc-\1"', body)
body = body.replace('<title>Cat Town</title>', '')
css = css.replace(':root {', '.pm2-city {', 1)
css = re.sub(r'\n  @media \(prefers-color-scheme: dark\).*?\n', '\n', css)
css = re.sub(r'\n  :root\[data-theme="dark"\].*?\n', '\n', css)
css = css.replace('  html, body { height: 100%; }\n', '')
css = css.replace('  body { background: var(--sky); color: var(--ink); font-family: var(--body); overflow: hidden; }',
  '  .pm2-city { position: relative; height: calc(100svh - var(--header-height, 64px)); min-height: 600px; overflow: hidden; background: var(--sky); color: var(--ink); font-family: var(--body); }')
css = re.sub(r'#(stage|countN|countL|play|postcard|infoBody|infoClose|info)\b', r'#pcc-\1', css)
out = []
for ln in css.split('\n'):
    s = ln.strip()
    if not s or s.startswith(('/*', '.pm2-city', '@media', '--', '}')): out.append(ln); continue
    m = re.match(r'(\s*)([^{]+)\{(.*)', ln)
    out.append(f"{m.group(1)}{', '.join('.pm2-city ' + x.strip() for x in m.group(2).split(','))} {{{m.group(3)}" if m else ln)
css = '\n'.join(out)
def scope_media(mt):
    inner = re.sub(r'(^|\}\s*)([^{}]+)\{', lambda m: m.group(1) + ', '.join('.pm2-city ' + x.strip() for x in m.group(2).split(',')) + ' {', mt.group(2))
    return mt.group(1) + inner + '}'
css = re.sub(r'(@media \(max-width: 520px\) \{)(.*)\}', scope_media, css)
for c in ['top', 'dock', 'loading', 'info']:
    css = css.replace(f'.pm2-city .{c} {{ position: fixed;', f'.pm2-city .{c} {{ position: absolute;')
css = css.replace('.pm2-city body.ready .loading', '.pm2-city.ready .loading').replace('#pcc-stage { position: fixed; inset: 0; }', '#pcc-stage { position: absolute; inset: 0; }')
liquid = """{%- comment -%}
  PETME2 Cat Town (city engine v3): interactive 3D cat city. Generated by social/cat-town/build_shopify.py from viewer.html (catcity.html engine).
  Drag to look around, tap a house (owner's Instagram) or a building, slider grows the city, Save postcard. JS: assets/pm2-cat-city.js.
{%- endcomment -%}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@700;800;900&family=Nunito+Sans:wght@400;600;700&display=swap">
<style>""" + css + """
</style>
<section class="pm2-city" data-cat-city>
""" + body.strip() + """
</section>
<script>window.CITY = """ + city + """;</script>
<script type="module" src="{{ 'pm2-cat-city.js' | asset_url }}"></script>

{% schema %}
{
  "name": "PETME2 Cat Town",
  "tag": "div",
  "class": "pm2-cat-town-section",
  "settings": [
    { "type": "text", "id": "heading", "label": "Card heading", "default": "Build the town with us" },
    { "type": "text", "id": "instagram_handle", "label": "Instagram handle", "default": "@petme2" },
    { "type": "url", "id": "instagram_url", "label": "Instagram link" }
  ],
  "presets": [{ "name": "PETME2 Cat Town" }]
}
{% endschema %}
"""
open(T + 'sections/pm2-cat-town.liquid', 'w').write(liquid)
open(T + 'assets/pm2-cat-city.js', 'w').write(js)
print('shopify files built', len(liquid), len(js))
